---
name: "LikeLoveHate"
guid: "a7b3c1d2-4e5f-6789-abcd-ef0123456789"
version: "1.2.3.0"
targetAbi: "10.9.0.0"
framework: "net9.0"
overview: "React to media with Like, Love, or Hate"
description: >
  A Jellyfin plugin that adds Like, Love, and Hate reaction buttons
  to media item detail pages. Users can react to any item and see
  community reactions at a glance.
category: "General"
owner: "DrBiznes"
artifacts:
- "Jellyfin.Plugin.LikeLoveHate.dll"
changelog: >
  Fixed item ID detection for Jellyfin 10.11+ (32-char hex IDs).
  Reaction buttons now appear in header row and video player OSD.
  Configurable reaction colors in plugin settings.
