---
name: "LikeLoveHate"
guid: "a7b3c1d2-4e5f-6789-abcd-ef0123456789"
version: "1.3.0.0"
targetAbi: "10.9.0.0"
framework: "net9.0"
overview: "React to media with Like, Love, or Hate"
description: >
  A Jellyfin plugin that adds Like, Love, and Hate reaction buttons
  to media item detail pages. Users can react to any item and see
  community reactions at a glance.
category: "General"
owner: "DrBiznes"
artifacts:
- "Jellyfin.Plugin.LikeLoveHate.dll"
changelog: >
  v1.3.0.0 - Major Robustness Update

  - Fixed "disappearing reactions" bug by implementing a backend Singleton Pattern.

  - Fixed OSD Sync: Reactions in the video player now correctly sync to the Series/Movie page.

  - New Feature: Import/Export reactions via JSON.

  - New Feature: "Wipe All Reactions" button (Danger Zone).

  - Enhanced UI: Reactions now display as compact chips with User Avatars.

  - Fixed Profile Page bug: Reactions panel no longer appears on User Profiles.
